#!/bin/bash
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
export ADLC=$(cd haskell; stack exec --docker which -- adlc)
export HXADLHS=$ROOT/scripts/hx-adl-hs
node $ROOT/typescript/hx-adl/build/main.js "$@"
